name = "aio" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "free.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free.bmkg.xyz"
custom_domain = true
